# Generated by Django 4.2.7 on 2026-07-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('specialization', models.CharField(db_index=True, max_length=255)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doctors',
                'indexes': [models.Index(fields=['specialization'], name='doctors_special_6661e0_idx'), models.Index(fields=['created_at'], name='doctors_created_7caef5_idx')],
            },
        ),
    ]
